name: raumunikate
description: Raumunikate
version: 0.0.1

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  go_router: ^17.0.0
  http: ^1.6.0
  provider: ^6.1.5+1
  transparent_image: ^2.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  very_good_analysis: ^10.0.0

flutter:
  assets:
    - images/
    - images/blog/
    - images/blog/0/
    - images/blog/1/
    - images/icons/
  fonts:
    - family: CourierPrime
      fonts:
        - asset: google_fonts/CourierPrime-Bold.ttf
          weight: 700
        - asset: google_fonts/CourierPrime-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: google_fonts/Roboto-Regular.ttf
          weight: 400
    - family: RobotoCondensed
      fonts:
        - asset: google_fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: google_fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: google_fonts/RobotoCondensed-Regular.ttf
          weight: 400
